#! /usr/bin/env python
#
# This file is part of Elements.
# Copyright (c) 2010 Sean Kerr. All rights reserved.
#
# The full license is available in the LICENSE file that was distributed with this source code.
#
# Author: Noah Fontes <nfontes@invectorate.com>

import webob
import itertools
try: import cStringIO as StringIO
except ImportError: import StringIO

from elements.async.impl.fastcgi import FastcgiClient
from elements.async.impl.fastcgi import FastcgiServer

def htmlspecialchars(v):
    if v is not None:
        try:
            table = { '&': '&amp;',
                      '>': '&gt;',
                      '<': '&lt;',
                      '"': '&quot;' }
            return ''.join([table[c] if c in table else c for c in v])
        except:
            pass
    return v

def htmlspecialchars_tuple(t):
    return (htmlspecialchars(t[0]), htmlspecialchars(t[1]))

class ExampleClient (FastcgiClient):

    def handle_dispatch (self):
        wsgi_params = dict(self.params)
        wsgi_params['wsgi.version'] = (1, 0)
        wsgi_params['wsgi.input'] = self.stdin
        wsgi_params['wsgi.errors'] = self.stderr
        wsgi_params['wsgi.url_scheme'] = 'https' if 'HTTPS' in self.params and self.params['HTTPS'].lower() in ('1', 'on') else 'http'
        wsgi_params['wsgi.multithread'] = False
        wsgi_params['wsgi.multiprocess'] = True

        request = webob.Request(wsgi_params)
        request.charset = 'utf-8'

        response = webob.Response()
        response.content_type = 'text/html'

        body = StringIO.StringIO()
        body.write("<h1>Success!</h1>")

        body.write("<h2>Raw</h2>")

        body.write("<h3>Raw Environment</h3>")
        for param in itertools.imap(htmlspecialchars_tuple, self.params.iteritems()):
            body.write("%s: <span style=\"color: #F00\">%s</span><br>" % param)

        body.write("<h3>Raw Input</h3>")
        body.write("<pre>%s</pre>" % htmlspecialchars(self.stdin.getvalue()))

        body.write("<h2>using webob.Request: %s</h2>" % htmlspecialchars(repr(request)))

        body.write("<h3>Environment</h3>")
        body.write("Scheme: <span style=\"color: #F00\">%s</span><br>" % htmlspecialchars(request.scheme))
        body.write("Method: <span style=\"color: #F00\">%s</span><br>" % htmlspecialchars(request.method))
        body.write("Script name: <span style=\"color: #F00\">%s</span><br>" % htmlspecialchars(request.script_name))
        body.write("Path info: <span style=\"color: #F00\">%s</span><br>" % htmlspecialchars(request.path_info))
        body.write("Content length: <span style=\"color: #F00\">%s</span><br>" % request.content_length)
        body.write("Remote user: <span style=\"color: #F00\">%s</span><br>" % htmlspecialchars(request.remote_user))
        body.write("Remote address: <span style=\"color: #F00\">%s</span><br>" % htmlspecialchars(request.remote_addr))
        body.write("Query string: <span style=\"color: #F00\">%s</span><br>" % htmlspecialchars(request.query_string))
        body.write("Server name: <span style=\"color: #F00\">%s</span><br>" % htmlspecialchars(request.server_name))
        body.write("Server port: <span style=\"color: #F00\">%s</span><br>" % request.server_port)

        body.write("<h3>Headers</h3>")
        for header in itertools.imap(htmlspecialchars_tuple, request.headers.iteritems()):
            body.write("%s: <span style=\"color: #F00\">%s</span><br>" % header)

        body.write("<h3>Cookies</h3>")
        for cookie in itertools.imap(htmlspecialchars_tuple, request.cookies.iteritems()):
            body.write("%s: <span style=\"color: #F00\">%s</span><br>" % cookie)

        body.write("<h3>Parameters</h3>")
        for param in itertools.imap(htmlspecialchars_tuple, request.params.iteritems()):
            body.write("%s: <span style=\"color: #F00\">%s</span><br>" % param)

        body.write("<h3>GET</h3>")
        for param in itertools.imap(htmlspecialchars_tuple, request.GET.iteritems()):
            body.write("%s: <span style=\"color: #F00\">%s</span><br>" % param)

        body.write("<h3>POST</h3>")
        for param in itertools.imap(htmlspecialchars_tuple, request.POST.iteritems()):
            body.write("%s: <span style=\"color: #F00\">%s</span><br>" % param)

        response.body = body.getvalue()
        body.close()

        # Try for a cookie, too!
        response.set_cookie('test', value = 'omgwtfbbq')

        result = request.get_response(response)

        data = StringIO.StringIO()
        data.write("%s %s\r\n" % (self.params["SERVER_PROTOCOL"], result.status))
        for header in result.headerlist:
            data.write("%s: %s\r\n" % header)
        data.write("\r\n")
        data.write(result.body)

        self.stdout.write(data.getvalue())

class ExampleServer (FastcgiServer):

    def handle_client (self, client_socket, client_address, server_address):
        """
        Register a new ExampleClient instance.
        """

        self.register_client(ExampleClient(client_socket, client_address, self, server_address))

if __name__ == "__main__":
    ExampleServer(hosts = [("0.0.0.0", 9010)]).start()
