#!/usr/bin/env python
#
# This file is part of Elements.
# Copyright (c) 2010 Sean Kerr. All rights reserved.
#
# The full license is available in the LICENSE file that was distributed with this source code.
#
# Author: Sean Kerr <sean@code-box.org>

import os
import sys

sys.path.append(os.path.abspath("../lib"))

from elements.async.server    import Server
from elements.async.impl.http import HttpRequest

# ----------------------------------------------------------------------------------------------------------------------

class ExampleHttpRequest (HttpRequest):

    def handle_finished (self):
        """
        This callback will be executed at the end of a successful request.
        """

        print self.in_headers
        print self.in_cookies
        print self.content_type
        print self.content_encoding
        print self.response_code
        print self.is_allowing_persistence
        print self.content

# ----------------------------------------------------------------------------------------------------------------------

class ExampleServer (Server):

    def handle_init (self):
        """
        This callback will be executed during the start of the process immediately before the processing loop starts.
        """

        request = ExampleHttpRequest(self, "search.yahoo.com")

        request.set_parameter("p",      "python elements")
        request.set_parameter("toggle", "1")
        request.set_parameter("cop",    "mss")
        request.set_parameter("ei",     "UTF-8")
        request.set_parameter("fr",     "yfp-t-892")

        request.open("/search")

# ----------------------------------------------------------------------------------------------------------------------

# start the server
ExampleServer().start()
