#!/usr/bin/env python
#
# This file is part of Elements.
# Copyright (c) 2010 Sean Kerr. All rights reserved.
#
# The full license is available in the LICENSE file that was distributed with this source code.
#
# Author: Sean Kerr <sean@code-box.org>

import os
import sys

sys.path.append(os.path.abspath("../lib"))

from elements.http.server import RegexRoutingHttpServer

# ----------------------------------------------------------------------------------------------------------------------

# start the server
RegexRoutingHttpServer(hosts=[("0.0.0.0", 8080)],
                       routes=[
                           [r"^/", "elements.http.action.TestHttpAction"],
                       ]).start()

"""
these are other routing methods, but for simplicities sake they're left out of the example server because
they would require several other files for them to work


this example here is good when you don't want to import an action class in the same file where the route is defined
this is also the required method of providing an action if you want to take advantage of the code reloading ability
that Elements provides
[r"^/path", "some.full.module.path.to.an.action.Class"]

action classes can also take arguments as a dictionary, but make sure you override the constructor in order to
receive them
[r"^/path", "some.Class", {"arg1": "just", "arg2": "a", "arg3": "test"}]

the elements.core.elements module contains an include() function that can be used to include other module attributes
as sub-routes. this allows for modules to be reusable.
[r"^/path", elements.include("mymodule.routes_attribute")]

"""
