#!/usr/bin/env python
#
# This file is part of Elements.
# Copyright (c) 2010 Sean Kerr. All rights reserved.
#
# The full license is available in the LICENSE file that was distributed with this source code.
#
# Author: Sean Kerr <sean@code-box.org>

import os
import sys

sys.path.append(os.path.abspath("../lib"))

from elements.async.impl.http import HttpAction
from elements.async.impl.http import RoutingHttpServer

# ----------------------------------------------------------------------------------------------------------------------

class ExampleAction (HttpAction):

    def get (self, client):
        """
        Handle a GET request.

        @param client (HttpClient) The HttpClient instance.
        """

        client.write("GET served")
        client.flush()

    # ------------------------------------------------------------------------------------------------------------------

    def post (self, client):
        """
        Handle a GET request.

        @param client (HttpClient) The HttpClient instance.
        """

        client.write("POST served")
        client.flush()

# ----------------------------------------------------------------------------------------------------------------------

class ExampleValidatingAction (HttpAction):

    def get (self, client):
        """
        Handle a GET request.

        Example request: GET /validate:42/justatest HTTP/1.1

        @param client (HttpClient) The HttpClient instance.
        """

        client.write("Parameters: " + str(client.params))
        client.flush()

# ----------------------------------------------------------------------------------------------------------------------

# start the server
RoutingHttpServer(hosts=[("0.0.0.0", 8080)],
                  routes={ "/":         ExampleAction,
                           "/validate": ("(number:\d+)/(word:\w+)", ExampleValidatingAction) }).start()
