#!/usr/bin/env python
#
# This file is part of Elements.
# Copyright (c) 2010 Sean Kerr. All rights reserved.
#
# The full license is available in the LICENSE file that was distributed with this source code.
#
# Author: Sean Kerr <sean@code-box.org>

import os
import sys

sys.path.append(os.path.abspath("../lib"))

from elements.http.action import HttpAction
from elements.http.server import RoutingHttpServer

# ----------------------------------------------------------------------------------------------------------------------

class ExampleArgsAction (HttpAction):

    def __init__ (self, sentence, **kwargs):
        """
        Create a new ExampleArgsAction instance.

        @param sentence (str) The sentence to repeat to the client.
        """

        HttpAction.__init__(self, **kwargs)

        self._sentence = sentence

    # ------------------------------------------------------------------------------------------------------------------

    def get (self, client):
        """
        Handle a GET request.

        @param client (HttpClient) The HttpClient instance.
        """

        client.compose_headers()
        client.write(self._sentence)

    # ------------------------------------------------------------------------------------------------------------------

    def post (self, client):
        """
        Handle a GET request.

        @param client (HttpClient) The HttpClient instance.
        """

        client.compose_headers()
        client.write(self._sentence)

# ----------------------------------------------------------------------------------------------------------------------

class ExampleValidatingAction (HttpAction):

    def get (self, client):
        """
        Handle a GET request.

        Example request: GET /validate:42/justatest HTTP/1.1

        @param client (HttpClient) The HttpClient instance.
        """

        client.compose_headers()
        client.write("Parameters: " + str(client.params))

# ----------------------------------------------------------------------------------------------------------------------

# start the server
RoutingHttpServer(hosts=[("0.0.0.0", 8080)],
                  routes=[
                           ["/", None, "elements.http.action.TestHttpAction"],

                           ["/sentence", None, ExampleArgsAction, {"sentence": "Hello, world! This is ExampleArgsAction!"}],

                           #["/static", "(file:.*)", "elements.http.action.StaticHttpAction", {"fs_root": os.getcwd() + "/static"}],

                           ["/validate", "(number:\d+)/(word:\w+)", ExampleValidatingAction]
                         ]).start()
